version: '3.8'

services:
  frontend:
    container_name: stockFRONTEND
    restart: always
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ./src:/src

networks:
  default:
    name: stock
